name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: josh-learning-LibraryManagementSystem
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./LibraryManagementSystem.sln

      - name: Build
        run: dotnet build ./LibraryManagementSystem.sln --configuration Release --no-restore

      - name: Test and Generate Code Coverage
        run: dotnet test ./UnitTests/UnitTests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Publish
        run: dotnet publish ./LibraryManagementSystem.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
