name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./LibraryManagementSystem.sln

      - name: Build
        run: dotnet build ./LibraryManagementSystem.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./LibraryManagementSystem.sln --configuration Release --no-build
